### ISSUE TITLE
Bug: Overflow issue on website

### ISSUE THREAD

**Issue by Asjas** [Asjas/Personal-Webpage#8]
### Issue Explanation
I am experiencing an overflow issue on the redesign of my personal website.

This is the [link](https://personalportfolio-riyczcgtsm.now.sh/) to a live version of the website. If you scroll down you'll see that there is a small amount of overflow below the side navigation. That overflow shouldn't be there. The sidebar needs to be flush at the bottom of the screen. From my testing, this is showing on Chrome and Firefox.

### Screenshot

![deepinscreenshot_20181021212824](https://user-images.githubusercontent.com/3828967/47271317-5eea3800-d578-11e8-8591-de9d203a5a1f.png)

### Code Explanation

The new version of my website is on the `feat/move-to-nextjs` branch on Github. Not `master`. This [link](https://github.com/Asjas/Personal-Webpage/tree/feat/move-to-nextjs) should open this repository on that branch. Anyone is free to take this issue and to open a pull request that fixes it. Most of the styles are in the `pages/styles` directory and the `src` directory.

**Comment by TechiePriyaRanjan** [comment]
I've fixed the error (overflow code). check the pull request. It's work fine😉 
sometime this single line of code can fix `overflow: hidden;` 👨‍💻

**Comment by Asjas** [comment]
The link to the new copy of the website is [here](https://personalportfolio-sicuhqhyod.now.sh/). It has 2 pages that are longer than the height of the browser and then still has 2 pages that aren't that long. The overflow issue needs to be fixed so that the 2 pages that aren't longer than the height don't have an overflow anymore. But the pages that are longer than the height should still display the entire content, it shouldn't be cut-off due to the overflow being hidden.

**Comment by eyalrosenbaum** [comment]
Hey, I've played around a bit, and I think the problem is that you gave the footers an absolute size of 150px; If you're using grid and 100vh for the whole body, I usually prefer to set big blocks of the screen in percents. Either way, if you're removing the absolute height of 150px of the footers, you won't have the extra space on the footers (all 3 screens). You can fix the padding issue by putting box-sizing:border-box and add padding-top on the footers.

**Comment by eyalrosenbaum** [comment]
I would like to try and fix this issue

**Comment by Asjas** [comment]
This has been fixed in #11

**Comment by elsonlim** [comment]
Hi @Asjas, I'd like to reopen this issue. The reason was related to the svg links, but not the size of the viewbox. I know #11 was merged in, but do take a look at #14. I wanted to submit the PR much earlier, but Github servers were wonky.
